// Die 89 Edelsteine von Fame – Stufe 1 (Malachit) bis Stufe 89 (Diamant).
//
// cut:  brilliant (Facettenschliff), oval (ovaler Facettenschliff), step (Treppenschliff),
//       cabochon (gewölbt, ohne Facetten)
// look: clear (durchsichtig), milk (milchig), opaque (undurchsichtig mit Muster),
//       opal (Farbspiel), labra (Farbschimmer), moon (bläulicher Schimmer), star (Sternstein),
//       diamond (der Diamant)
// pattern (für Cabochons): bands, clouds, flecks, dendrite, matrix, glitter, veins
// c = Hauptfarbe, c2 = zweite Farbe (Muster, Bicolor, Farbwechsel)

const G = (name, c, cut = 'brilliant', look = 'clear', extra = {}) => ({ name, c, cut, look, ...extra });

export const GEM_LIST = [
  G('Malachit', '#1c8a4a', 'cabochon', 'opaque', { pattern: 'bands', c2: '#0b3f22' }),
  G('Larimar', '#5cc4e2', 'cabochon', 'opaque', { pattern: 'clouds', c2: '#eefcff' }),
  G('Mondstein', '#d6e2f4', 'cabochon', 'moon'),
  G('Chalzedon', '#86a3cf', 'cabochon', 'milk'),
  G('Lapislazuli', '#1f3aa0', 'cabochon', 'opaque', { pattern: 'flecks', c2: '#e8c25a' }),
  G('Dendritenachat', '#d6cfc0', 'cabochon', 'opaque', { pattern: 'dendrite', c2: '#2a2622' }),
  G('Rauchquarz', '#6e5440'),
  G('Chrysopras', '#47c27a', 'cabochon', 'milk'),
  G('Sonnenstein', '#e07a32', 'cabochon', 'opaque', { pattern: 'glitter', c2: '#ffd08a' }),
  G('Weißtopas', '#f2f6fb', 'oval'),
  G('Rosenquarz', '#ee98b0', 'cabochon', 'milk'),
  G('Spektrolith', '#26323f', 'cabochon', 'labra', { c2: '#3fd0ff' }),
  G('Bergkristall', '#eef4fc'),
  G('Rutilquarz', '#efe6d0', 'oval', 'clear', { c2: '#d4a43a' }),
  G('Labradorit', '#36424e', 'cabochon', 'labra', { c2: '#3f8cff' }),
  G('Fibrolith', '#b3a998', 'cabochon', 'milk'),
  G('Swiss-Blue-Topas', '#4cc2ea'),
  G('Sky-Blue-Topas', '#a2dcf3', 'oval'),
  G('Prasiolith', '#b4e2a4', 'step'),
  G('Amethyst', '#9a56d2', 'oval'),
  G('London-Blue-Topas', '#1e5888'),
  G('Granat', '#8c1a1e'),
  G('Citrin', '#f2af38', 'step'),
  G('Naturblauer Topas', '#8ac8e6', 'oval'),
  G('Blautopas', '#3ea8e0'),
  G('Skapolith', '#f0d878', 'oval'),
  G('Diopsid', '#2e6a3a'),
  G('Champagner-Topas', '#e6c79a', 'step'),
  G('Fluorit', '#8f7ee0', 'step', 'clear', { c2: '#6ad49e', bicolor: true }),
  G('Kyanit', '#2c5db8', 'oval'),
  G('Chromdiopsid', '#1b7a3c'),
  G('Koroit-Boulder-Opal', '#5a3a22', 'cabochon', 'opal', { c2: '#3a2414' }),
  G('Goldberyll', '#f0be3e', 'step'),
  G('Iolith', '#4a4eb2', 'oval'),
  G('Achroit', '#f4f6f0', 'step'),
  G('Beryll', '#c6e6d0', 'step'),
  G('Welo-Opal', '#f0e4cc', 'cabochon', 'opal', { c2: '#fff4e0' }),
  G('Sugilith', '#6a2a8c', 'cabochon', 'opaque', { pattern: 'clouds', c2: '#3a1450' }),
  G('Rhodolith', '#b0284e'),
  G('Türkis', '#3ec8c0', 'cabochon', 'opaque', { pattern: 'matrix', c2: '#5a4834' }),
  G('Kunzit', '#f2b6dc', 'step'),
  G('Andalusit', '#8a6a3a', 'oval', 'clear', { c2: '#5c7a36', bicolor: true }),
  G('Titanit', '#c6d43a'),
  G('Morganit', '#f6c0b2', 'step'),
  G('Peridot', '#9cca38', 'oval'),
  G('Rhodonit', '#d2567a', 'cabochon', 'opaque', { pattern: 'veins', c2: '#1e1a1a' }),
  G('Siberit', '#c2185a', 'step'),
  G('Apatit', '#2ec4c6'),
  G('Sternsaphir', '#34489a', 'cabochon', 'star'),
  G('Rubellit', '#d81b5e', 'step'),
  G('Yowah-Boulder-Opal', '#6a4426', 'cabochon', 'opal', { c2: '#40281a' }),
  G('Bicolor-Turmalin', '#e8507a', 'step', 'clear', { c2: '#4caf50', bicolor: true }),
  G('Turmalin', '#3a8a5a', 'step'),
  G('Verdelith', '#2e7d32', 'step'),
  G('Goldtopas', '#f5a523', 'oval'),
  G('Boulder-Opal', '#4a3020', 'cabochon', 'opal', { c2: '#2a1a10' }),
  G('Hessonit', '#c8641e'),
  G('Zirkon', '#a6dcf2'),
  G('Aquamarin', '#7fd4e8', 'step'),
  G('Opal', '#eae6e0', 'cabochon', 'opal', { c2: '#ffffff' }),
  G('Pyrop', '#9a0f1e'),
  G('Spessartin', '#ff6a14'),
  G('Indigolith', '#1a3e8a', 'step'),
  G('Feueropal', '#ff781a', 'oval'),
  G('Crystal Opal', '#dce6ee', 'cabochon', 'opal', { c2: '#f4f8fc' }),
  G('White Opal', '#f2f0ec', 'cabochon', 'opal', { c2: '#ffffff' }),
  G('Chrysoberyll', '#d6d23a', 'oval'),
  G('Imperial-Topas', '#f08824', 'step'),
  G('Chromturmalin', '#0f8a3a', 'step'),
  G('Sternrubin', '#b0102c', 'cabochon', 'star'),
  G('Spinell', '#e0204a'),
  G('Black Crystal Opal', '#1e2026', 'cabochon', 'opal', { c2: '#0e1014' }),
  G('Gelber Saphir', '#ffd21e', 'oval'),
  G('Tansanit', '#4b3ec2', 'oval'),
  G('Semi Black Opal', '#3a3c44', 'cabochon', 'opal', { c2: '#24262c' }),
  G('Tsavorit', '#1eae4a'),
  G('Jeremejewit', '#8ecff0', 'oval'),
  G('Black Opal', '#121318', 'cabochon', 'opal', { c2: '#08090c' }),
  G('Grüner Saphir', '#2e8e5a', 'oval'),
  G('Padparadscha-Saphir', '#ff9a7a', 'oval'),
  G('Demantoid', '#5ed03a'),
  G('Violetter Saphir', '#8a3ed2', 'oval'),
  G('Saphir', '#1d3ebf', 'oval'),
  G('Rosa Saphir', '#ff6eae', 'oval'),
  G('Smaragd', '#0f9a5a', 'step', 'clear', { flavor: 'Grün vor Neid – die anderen.' }),
  G('Rubin', '#d40f3a', 'oval', 'clear', { flavor: 'Rot wie der Teppich, auf dem du stehst.' }),
  G('Alexandrit', '#2f8a6a', 'brilliant', 'clear', { c2: '#a02e6a', shift: true, flavor: 'Wechselt die Farbe. Nicht den Charakter.' }),
  G('Paraíba-Turmalin', '#1ee2e0', 'oval', 'clear', { glow: true, flavor: 'Leuchtet heller als jede Clubnacht.' }),
  G('Diamant', '#ffffff', 'brilliant', 'diamond', { flavor: 'Erst Fame, dann die anderen.' }),
];

// Sprüche je Seltenheitsklasse, falls ein Stein keinen eigenen hat
export const BAND_FLAVOR = [
  'Jeder fängt mal klein an.',
  'Ein Funkeln, das auffällt.',
  'Jetzt schauen die Leute hin.',
  'Selten. Wie du.',
  'Kaum einer hat ihn. Du schon.',
];

// Stufe -> Seltenheitsklasse (0..4): bestimmt Farben, Sound und Effekte – nicht den Stein selbst.
export function bandFor(stage) {
  return stage <= 25 ? 0 : stage <= 50 ? 1 : stage <= 70 ? 2 : stage <= 82 ? 3 : 4;
}
