// Englische (US) Namen und Sprüche der Edelsteine – Schlüssel ist der deutsche Name aus js/gems.js
export const GEM_NAMES_EN = {
  'Malachit': "Malachite",
  'Larimar': "Larimar",
  'Mondstein': "Moonstone",
  'Chalzedon': "Chalcedony",
  'Lapislazuli': "Lapis Lazuli",
  'Dendritenachat': "Dendritic Agate",
  'Rauchquarz': "Smoky Quartz",
  'Chrysopras': "Chrysoprase",
  'Sonnenstein': "Sunstone",
  'Weißtopas': "White Topaz",
  'Rosenquarz': "Rose Quartz",
  'Spektrolith': "Spectrolite",
  'Bergkristall': "Rock Crystal",
  'Rutilquarz': "Rutilated Quartz",
  'Labradorit': "Labradorite",
  'Fibrolith': "Fibrolite",
  'Swiss-Blue-Topas': "Swiss Blue Topaz",
  'Sky-Blue-Topas': "Sky Blue Topaz",
  'Prasiolith': "Prasiolite",
  'Amethyst': "Amethyst",
  'London-Blue-Topas': "London Blue Topaz",
  'Granat': "Garnet",
  'Citrin': "Citrine",
  'Naturblauer Topas': "Natural Blue Topaz",
  'Blautopas': "Blue Topaz",
  'Skapolith': "Scapolite",
  'Diopsid': "Diopside",
  'Champagner-Topas': "Champagne Topaz",
  'Fluorit': "Fluorite",
  'Kyanit': "Kyanite",
  'Chromdiopsid': "Chrome Diopside",
  'Koroit-Boulder-Opal': "Koroit Boulder Opal",
  'Goldberyll': "Golden Beryl",
  'Iolith': "Iolite",
  'Achroit': "Achroite",
  'Beryll': "Beryl",
  'Welo-Opal': "Welo Opal",
  'Sugilith': "Sugilite",
  'Rhodolith': "Rhodolite",
  'Türkis': "Turquoise",
  'Kunzit': "Kunzite",
  'Andalusit': "Andalusite",
  'Titanit': "Titanite",
  'Morganit': "Morganite",
  'Peridot': "Peridot",
  'Rhodonit': "Rhodonite",
  'Siberit': "Siberite",
  'Apatit': "Apatite",
  'Sternsaphir': "Star Sapphire",
  'Rubellit': "Rubellite",
  'Yowah-Boulder-Opal': "Yowah Boulder Opal",
  'Bicolor-Turmalin': "Bicolor Tourmaline",
  'Turmalin': "Tourmaline",
  'Verdelith': "Verdelite",
  'Goldtopas': "Golden Topaz",
  'Boulder-Opal': "Boulder Opal",
  'Hessonit': "Hessonite",
  'Zirkon': "Zircon",
  'Aquamarin': "Aquamarine",
  'Opal': "Opal",
  'Pyrop': "Pyrope",
  'Spessartin': "Spessartite",
  'Indigolith': "Indicolite",
  'Feueropal': "Fire Opal",
  'Crystal Opal': "Crystal Opal",
  'White Opal': "White Opal",
  'Chrysoberyll': "Chrysoberyl",
  'Imperial-Topas': "Imperial Topaz",
  'Chromturmalin': "Chrome Tourmaline",
  'Sternrubin': "Star Ruby",
  'Spinell': "Spinel",
  'Black Crystal Opal': "Black Crystal Opal",
  'Gelber Saphir': "Yellow Sapphire",
  'Tansanit': "Tanzanite",
  'Semi Black Opal': "Semi Black Opal",
  'Tsavorit': "Tsavorite",
  'Jeremejewit': "Jeremejevite",
  'Black Opal': "Black Opal",
  'Grüner Saphir': "Green Sapphire",
  'Padparadscha-Saphir': "Padparadscha Sapphire",
  'Demantoid': "Demantoid",
  'Violetter Saphir': "Violet Sapphire",
  'Saphir': "Sapphire",
  'Rosa Saphir': "Pink Sapphire",
  'Smaragd': "Emerald",
  'Rubin': "Ruby",
  'Alexandrit': "Alexandrite",
  'Paraíba-Turmalin': "Paraíba Tourmaline",
  'Diamant': "Diamond",
  'The Orange': "The Orange",
  'The Unique Pink': "The Unique Pink",
  'De Beers Millennium Jewel 4': "De Beers Millennium Jewel 4",
  'Graff Pink': "Graff Pink",
  'Blue Moon of Josephine': "Blue Moon of Josephine",
  'Pink Legacy': "Pink Legacy",
  'Oppenheimer Blue': "Oppenheimer Blue",
  'The Constellation': "The Constellation",
  'Lesedi La Rona': "Lesedi La Rona",
  'The Pink Star': "The Pink Star",
  'Hope-Diamant': "Hope Diamond",
};

export const SAYINGS_EN = {
  'Malachit': "First stone, first aura. Lowkey a flex.",
  'Larimar': "Caribbean vibes, pocket-sized. That's wild.",
  'Mondstein': "Glows at night. So do you, no cap.",
  'Chalzedon': "Chill aura activated. Respect, bro.",
  'Lapislazuli': "Blue with gold flecks. It's giving royal drip.",
  'Dendritenachat': "A whole forest in a stone. Main character energy.",
  'Rauchquarz': "Smoky, mysterious, lowkey too cool.",
  'Chrysopras': "Fresh like your glow-up.",
  'Sonnenstein': "Sun's up, aura's up.",
  'Weißtopas': "Clean. Clear. Iconic.",
  'Rosenquarz': "Soft era, hard flex.",
  'Spektrolith': "Every color, zero NPC energy.",
  'Bergkristall': "Clearer than your weekend plans.",
  'Rutilquarz': "Gold threads in glass. Drip since the Stone Age.",
  'Labradorit': "Looks basic, then: sheesh.",
  'Fibrolith': "Nobody knows it. That's the flex.",
  'Swiss-Blue-Topas': "Alpine vibes, summit aura.",
  'Sky-Blue-Topas': "Sky's not the limit. You are.",
  'Prasiolith': "Everyone else is green with envy. W.",
  'Amethyst': "Purple era unlocked. Understood the assignment.",
  'London-Blue-Topas': "Deep blue like your nightlife. Wild.",
  'Granat': "Deep red and loyal. A ride-or-die stone.",
  'Citrin': "Yellow, good mood, treating itself.",
  'Naturblauer Topas': "Natural glow. No filter needed.",
  'Blautopas': "Not feeling blue. Flexing blue.",
  'Skapolith': "Barely anyone knows it. You do. Goated.",
  'Diopsid': "Dark green with depth. Real talk.",
  'Champagner-Topas': "Champagne mood, zero hangover.",
  'Fluorit': "Two colors, one vibe. Slay.",
  'Kyanit': "Blue with edges and attitude. Like you.",
  'Chromdiopsid': "Siberian cold, but everyone's hot for it.",
  'Koroit-Boulder-Opal': "Fireworks in the rock. Sheesh!",
  'Goldberyll': "Gold that doesn't need to flex. Does anyway.",
  'Iolith': "Viking compass. Direction: only up.",
  'Achroit': "Colorless? More like flawless.",
  'Beryll': "Emerald fam. You're a cousin now.",
  'Welo-Opal': "Rainbow to go. The vibe is immaculate.",
  'Sugilith': "Rarer than 80% battery at night.",
  'Rhodolith': "Rose red and full of rizz.",
  'Türkis': "Pharaoh aura. Egypt approved.",
  'Kunzit': "Soft pink, but main character.",
  'Andalusit': "Switches colors, never the style.",
  'Titanit': "More fire than a diamond. Shh, don't tell.",
  'Morganit': "Peach, rosé, pure treat-yourself.",
  'Peridot': "Born in a volcano. That's crazy.",
  'Rhodonit': "Pink with tattoo lines. Hard.",
  'Siberit': "Ice cold from Siberia, hot on the 'gram.",
  'Apatit': "Neon blue. Nobody's scrolling past this.",
  'Sternsaphir': "You're wearing a literal star. Not fake.",
  'Rubellit': "Pinkish red and totally unbothered.",
  'Yowah-Boulder-Opal': "Outback lore unlocked.",
  'Bicolor-Turmalin': "Two sides, both fire.",
  'Turmalin': "Does every color. Does every flex.",
  'Verdelith': "Green, glossy, goated.",
  'Goldtopas': "Golden hour, but forever.",
  'Boulder-Opal': "Fire in the rock. Aura in the sky.",
  'Hessonit': "Cinnamon, honey, main character.",
  'Zirkon': "Older than mountains, fresher than your feed.",
  'Aquamarin': "Ocean vibes. You make your own waves.",
  'Opal': "Every glance, a new filter.",
  'Pyrop': "Fire red. Don't touch, too hot.",
  'Spessartin': "Tangerine drip. Juicy.",
  'Indigolith': "Deep blue and rare as Wi-Fi on a train.",
  'Feueropal': "Burns without burning out. You: on fire.",
  'Crystal Opal': "Clear as glass, loud as a festival.",
  'White Opal': "White, but zero basic.",
  'Chrysoberyll': "Gold-green and tougher than your Monday.",
  'Imperial-Topas': "Made for czars. Now it's your era.",
  'Chromturmalin': "Emerald green with a mind of its own. Unbothered.",
  'Sternrubin': "A star in red. Can't get much more Fame.",
  'Spinell': "Once a ruby stunt double, now the star.",
  'Black Crystal Opal': "Dark mode, but in color.",
  'Gelber Saphir': "Sunshine with sapphire armor. Unbreakable.",
  'Tansanit': "Found in one place on Earth. Now on you.",
  'Semi Black Opal': "Half night, all fireworks.",
  'Tsavorit': "Greener than everyone's envy. Easy W.",
  'Jeremejewit': "Nobody can say it. Everybody wants it.",
  'Black Opal': "King of opals. And you're the final boss.",
  'Grüner Saphir': "Green with sapphire power. Built different.",
  'Padparadscha-Saphir': "Sunset vibes in stone. Ate.",
  'Demantoid': "Sparkles harder than a diamond. Sorry, diamond.",
  'Violetter Saphir': "Violet, elegant, absolute aura.",
  'Saphir': "Crown jewel energy. You run this.",
  'Rosa Saphir': "Barbie pink with a backbone.",
  'Smaragd': "Everyone's green with envy. You: chillin'.",
  'Rubin': "Red carpet under your feet. Sheesh.",
  'Alexandrit': "Changes color, never the vibe.",
  'Paraíba-Turmalin': "Glows brighter than any club night.",
  'Diamant': "Fame first, then the others. Forever.",
  'The Orange': "Fire in a teardrop. And you're even hotter.",
  'The Unique Pink': "Unique like you. No dupe possible.",
  'De Beers Millennium Jewel 4': "A once-in-a-millennium stone. Your millennium flex.",
  'Graff Pink': "Intense. Just like your entrance.",
  'Blue Moon of Josephine': "Happens once in a blue moon. So, now.",
  'Pink Legacy': "Legacy unlocked. You write the lore.",
  'Oppenheimer Blue': "The deepest blue. The highest aura.",
  'The Constellation': "A whole constellation, and you're the brightest star.",
  'Lesedi La Rona': "\"Our Light\", now yours. GOAT status.",
  'The Pink Star': "Most expensive stone ever auctioned. Now it's yours.",
  'Bleu Royal': "Royal blue? No: royal you.",
  'De Beers Blue': "Almost the blue record. You are it.",
  'Williamson Pink Star': "Pink, flawless, star status.",
  'Sancy': "Worn by kings. Now by you.",
  'Koh-i-Noor': "\"Mountain of Light\"? You're standing on top.",
  'Hope-Diamant': "The Heart of the Ocean? You're wearing it now.",
  'Cullinan I': "Doesn't get bigger. Final boss defeated.",
};
