// Die 89 Edelsteine von Fame – Stufe 1 (Malachit) bis Stufe 89 (Diamant).
//
// cut:  Brillant-Familie: round, oval, cushion, cushionSquare, marquise, pear, princess, radiant,
//       radiantSquare – Treppenschliffe: emerald (ratio = Länge zu Breite), asscher, octagon –
//       cabochon (gewölbt, ohne Facetten). Typischer Schliff je Stein: siehe CUTS unten.
// look: clear (durchsichtig), milk (milchig), opaque (undurchsichtig mit Muster),
//       opal (Farbspiel), labra (Farbschimmer), moon (bläulicher Schimmer), star (Sternstein),
//       diamond (der Diamant)
// pattern (für Cabochons): bands, clouds, flecks, dendrite, matrix, glitter, veins
// c = Hauptfarbe, c2 = zweite Farbe (Muster, Bicolor, Farbwechsel)

const G = (name, c, cut = 'brilliant', look = 'clear', extra = {}) => ({ name, c, cut, look, ...extra });

export const GEM_LIST = [
  G('Malachit', '#1c8a4a', 'cabochon', 'opaque', { pattern: 'bands', c2: '#0b3f22' }),
  G('Larimar', '#5cc4e2', 'cabochon', 'opaque', { pattern: 'clouds', c2: '#eefcff' }),
  G('Mondstein', '#d6e2f4', 'cabochon', 'moon'),
  G('Chalzedon', '#86a3cf', 'cabochon', 'milk'),
  G('Lapislazuli', '#1f3aa0', 'cabochon', 'opaque', { pattern: 'flecks', c2: '#e8c25a' }),
  G('Dendritenachat', '#d6cfc0', 'cabochon', 'opaque', { pattern: 'dendrite', c2: '#2a2622' }),
  G('Rauchquarz', '#6e5440'),
  G('Chrysopras', '#47c27a', 'cabochon', 'milk'),
  G('Sonnenstein', '#e07a32', 'cabochon', 'opaque', { pattern: 'glitter', c2: '#ffd08a' }),
  G('Weißtopas', '#f2f6fb', 'oval'),
  G('Rosenquarz', '#ee98b0', 'cabochon', 'milk'),
  G('Spektrolith', '#26323f', 'cabochon', 'labra', { c2: '#3fd0ff' }),
  G('Bergkristall', '#eef4fc'),
  G('Rutilquarz', '#efe6d0', 'oval', 'clear', { c2: '#d4a43a' }),
  G('Labradorit', '#36424e', 'cabochon', 'labra', { c2: '#3f8cff' }),
  G('Fibrolith', '#b3a998', 'cabochon', 'milk'),
  G('Swiss-Blue-Topas', '#4cc2ea'),
  G('Sky-Blue-Topas', '#a2dcf3', 'oval'),
  G('Prasiolith', '#b4e2a4', 'step'),
  G('Amethyst', '#9a56d2', 'oval'),
  G('London-Blue-Topas', '#1e5888'),
  G('Granat', '#8c1a1e'),
  G('Citrin', '#f2af38', 'step'),
  G('Naturblauer Topas', '#8ac8e6', 'oval'),
  G('Blautopas', '#3ea8e0'),
  G('Skapolith', '#f0d878', 'oval'),
  G('Diopsid', '#2e6a3a'),
  G('Champagner-Topas', '#e6c79a', 'step'),
  G('Fluorit', '#8f7ee0', 'step', 'clear', { c2: '#6ad49e', bicolor: true }),
  G('Kyanit', '#2c5db8', 'oval'),
  G('Chromdiopsid', '#1b7a3c'),
  G('Koroit-Boulder-Opal', '#5a3a22', 'cabochon', 'opal', { c2: '#3a2414' }),
  G('Goldberyll', '#f0be3e', 'step'),
  G('Iolith', '#4a4eb2', 'oval'),
  G('Achroit', '#f4f6f0', 'step'),
  G('Beryll', '#c6e6d0', 'step'),
  G('Welo-Opal', '#f0e4cc', 'cabochon', 'opal', { c2: '#fff4e0' }),
  G('Sugilith', '#6a2a8c', 'cabochon', 'opaque', { pattern: 'clouds', c2: '#3a1450' }),
  G('Rhodolith', '#b0284e'),
  G('Türkis', '#3ec8c0', 'cabochon', 'opaque', { pattern: 'matrix', c2: '#5a4834' }),
  G('Kunzit', '#f2b6dc', 'step'),
  G('Andalusit', '#8a6a3a', 'oval', 'clear', { c2: '#5c7a36', bicolor: true }),
  G('Titanit', '#c6d43a'),
  G('Morganit', '#f6c0b2', 'step'),
  G('Peridot', '#9cca38', 'oval'),
  G('Rhodonit', '#d2567a', 'cabochon', 'opaque', { pattern: 'veins', c2: '#1e1a1a' }),
  G('Siberit', '#c2185a', 'step'),
  G('Apatit', '#2ec4c6'),
  G('Sternsaphir', '#34489a', 'cabochon', 'star'),
  G('Rubellit', '#d81b5e', 'step'),
  G('Yowah-Boulder-Opal', '#6a4426', 'cabochon', 'opal', { c2: '#40281a' }),
  G('Bicolor-Turmalin', '#e8507a', 'step', 'clear', { c2: '#4caf50', bicolor: true }),
  G('Turmalin', '#3a8a5a', 'step'),
  G('Verdelith', '#2e7d32', 'step'),
  G('Goldtopas', '#f5a523', 'oval'),
  G('Boulder-Opal', '#4a3020', 'cabochon', 'opal', { c2: '#2a1a10' }),
  G('Hessonit', '#c8641e'),
  G('Zirkon', '#a6dcf2'),
  G('Aquamarin', '#7fd4e8', 'step'),
  G('Opal', '#eae6e0', 'cabochon', 'opal', { c2: '#ffffff' }),
  G('Pyrop', '#9a0f1e'),
  G('Spessartin', '#ff6a14'),
  G('Indigolith', '#1a3e8a', 'step'),
  G('Feueropal', '#ff781a', 'oval'),
  G('Crystal Opal', '#dce6ee', 'cabochon', 'opal', { c2: '#f4f8fc' }),
  G('White Opal', '#f2f0ec', 'cabochon', 'opal', { c2: '#ffffff' }),
  G('Chrysoberyll', '#d6d23a', 'oval'),
  G('Imperial-Topas', '#f08824', 'step'),
  G('Chromturmalin', '#0f8a3a', 'step'),
  G('Sternrubin', '#b0102c', 'cabochon', 'star'),
  G('Spinell', '#e0204a'),
  G('Black Crystal Opal', '#1e2026', 'cabochon', 'opal', { c2: '#0e1014' }),
  G('Gelber Saphir', '#ffd21e', 'oval'),
  G('Tansanit', '#4b3ec2', 'oval'),
  G('Semi Black Opal', '#3a3c44', 'cabochon', 'opal', { c2: '#24262c' }),
  G('Tsavorit', '#1eae4a'),
  G('Jeremejewit', '#8ecff0', 'oval'),
  G('Black Opal', '#121318', 'cabochon', 'opal', { c2: '#08090c' }),
  G('Grüner Saphir', '#2e8e5a', 'oval'),
  G('Padparadscha-Saphir', '#ff9a7a', 'oval'),
  G('Demantoid', '#5ed03a'),
  G('Violetter Saphir', '#8a3ed2', 'oval'),
  G('Saphir', '#1d3ebf', 'oval'),
  G('Rosa Saphir', '#ff6eae', 'oval'),
  G('Smaragd', '#0f9a5a', 'step', 'clear', { flavor: 'Grün vor Neid – die anderen.' }),
  G('Rubin', '#d40f3a', 'oval', 'clear', { flavor: 'Rot wie der Teppich, auf dem du stehst.' }),
  G('Alexandrit', '#2f8a6a', 'brilliant', 'clear', { c2: '#a02e6a', shift: true, flavor: 'Wechselt die Farbe. Nicht den Charakter.' }),
  G('Paraíba-Turmalin', '#1ee2e0', 'oval', 'clear', { glow: true, flavor: 'Leuchtet heller als jede Clubnacht.' }),
  G('Diamant', '#ffffff', 'round', 'diamond', { flavor: 'Erst Fame, dann die anderen.' }),

  // Die Legenden: berühmte Diamanten ab 300.000 € bis 1 Mio. €
  G('Orangefarbener Diamant', '#ff8a1c', 'pear', 'diamond', { legend: true, flavor: 'Feuer in Tropfenform.' }),
  G('The Unique Pink', '#ff7fb6', 'pear', 'diamond', { legend: true, flavor: 'Einzigartig. Wie der Name sagt.' }),
  G('De Beers Millennium Jewel 4', '#4f8fff', 'oval', 'diamond', { legend: true, flavor: 'Blau wie die Tiefe des Ozeans.' }),
  G('Fancy Intense Pink', '#ff5fa2', 'radiant', 'diamond', { legend: true, flavor: 'Intensiv. Wie dein Auftritt.' }),
  G('Blue Moon of Josephine', '#5aa2ff', 'cushion', 'diamond', { legend: true, flavor: 'Einmal im blauen Mond.' }),
  G('Pink Legacy', '#ff6fa8', 'emerald', 'diamond', { legend: true, ratio: 1.3, flavor: 'Ein Vermächtnis in Rosa.' }),
  G('Oppenheimer Blue', '#3f7dff', 'emerald', 'diamond', { legend: true, ratio: 1.22, flavor: 'Das tiefste Blau der Welt.' }),
  G('The Constellation', '#ffffff', 'cushion', 'diamond', { legend: true, flavor: 'Ein ganzes Sternbild in deiner Hand.' }),
  G('Lesedi La Rona', '#ffffff', 'asscher', 'diamond', { legend: true, flavor: '„Unser Licht“ – jetzt deins.' }),
  G('The Pink Star', '#ff4f9a', 'oval', 'diamond', { legend: true, flavor: 'Der Stern über allen.' }),
];

// Typischer Schliff je Stein (für alle facettierten Steine außer den Legenden)
const CUTS = {
  'Rauchquarz': 'cushion', 'Weißtopas': 'round', 'Bergkristall': 'radiant', 'Rutilquarz': 'cushion',
  'Swiss-Blue-Topas': 'cushionSquare', 'Sky-Blue-Topas': 'oval', 'Prasiolith': 'octagon', 'Amethyst': 'oval',
  'London-Blue-Topas': 'emerald', 'Granat': 'round', 'Citrin': 'cushionSquare', 'Naturblauer Topas': 'marquise',
  'Blautopas': 'princess', 'Skapolith': 'oval', 'Diopsid': 'round', 'Champagner-Topas': 'emerald',
  'Fluorit': 'octagon', 'Kyanit': 'emerald', 'Chromdiopsid': 'cushionSquare', 'Goldberyll': 'emerald',
  'Iolith': 'cushion', 'Achroit': 'asscher', 'Beryll': 'emerald', 'Rhodolith': 'cushion',
  'Kunzit': 'radiant', 'Andalusit': 'oval', 'Titanit': 'round', 'Morganit': 'pear', 'Peridot': 'oval',
  'Siberit': 'emerald', 'Apatit': 'radiantSquare', 'Rubellit': 'cushion', 'Bicolor-Turmalin': 'emerald',
  'Turmalin': 'radiant', 'Verdelith': 'emerald', 'Goldtopas': 'pear', 'Hessonit': 'oval', 'Zirkon': 'round',
  'Aquamarin': 'emerald', 'Pyrop': 'round', 'Spessartin': 'cushionSquare', 'Indigolith': 'emerald',
  'Feueropal': 'oval', 'Chrysoberyll': 'cushion', 'Imperial-Topas': 'pear', 'Chromturmalin': 'octagon',
  'Spinell': 'cushion', 'Gelber Saphir': 'radiant', 'Tansanit': 'cushionSquare', 'Tsavorit': 'round',
  'Jeremejewit': 'oval', 'Grüner Saphir': 'asscher', 'Padparadscha-Saphir': 'cushion', 'Demantoid': 'round',
  'Violetter Saphir': 'marquise', 'Saphir': 'oval', 'Rosa Saphir': 'pear', 'Smaragd': 'emerald',
  'Rubin': 'cushion', 'Alexandrit': 'cushion', 'Paraíba-Turmalin': 'pear',
};

// Ein eigener Spruch für jede Card
const SAYINGS = {
  'Malachit': 'Grün gestreift, wie die ersten Scheine.',
  'Larimar': 'Ein Stück Karibik für die Tasche.',
  'Mondstein': 'Leuchtet auch, wenn das Licht ausgeht.',
  'Chalzedon': 'Ruhig im Ton, sicher im Auftritt.',
  'Lapislazuli': 'Blau wie Königsmäntel – mit Gold drin.',
  'Dendritenachat': 'Ein ganzer Wald im Stein. Du bist der höchste Baum.',
  'Rauchquarz': 'Rauch ohne Feuer? Nicht bei dir.',
  'Chrysopras': 'Apfelgrün und frisch auf der Liste.',
  'Sonnenstein': 'Hier geht die Sonne für dich auf.',
  'Weißtopas': 'Klar wie deine Ansage.',
  'Rosenquarz': 'Für die, die Herz zeigen.',
  'Spektrolith': 'Alle Farben, eine Haltung.',
  'Bergkristall': 'Klarheit von ganz oben.',
  'Rutilquarz': 'Goldfäden im Glas – so sieht Stil aus.',
  'Labradorit': 'Schimmert erst, wenn man genau hinsieht.',
  'Fibrolith': 'Selten gesehen, sofort gemerkt.',
  'Swiss-Blue-Topas': 'Kühl wie ein Bergsee in den Alpen.',
  'Sky-Blue-Topas': 'Blauer Himmel, keine Grenze.',
  'Prasiolith': 'Grün wie der erste Neid der anderen.',
  'Amethyst': 'Violett war schon immer Königsfarbe.',
  'London-Blue-Topas': 'Dunkelblau wie Londoner Nächte.',
  'Granat': 'Tiefrot. Treu. Unverwechselbar.',
  'Citrin': 'Sonnengelb und gut gelaunt.',
  'Naturblauer Topas': 'Natürlich blau. Natürlich du.',
  'Blautopas': 'Ein Blau, das hängen bleibt.',
  'Skapolith': 'Den kennt kaum einer. Genau deshalb.',
  'Diopsid': 'Dunkles Grün mit Tiefgang.',
  'Champagner-Topas': 'Champagner, der nie schal wird.',
  'Fluorit': 'Zwei Farben, ein Statement.',
  'Kyanit': 'Blau mit Ecken und Kanten.',
  'Chromdiopsid': 'Sattes Grün aus dem sibirischen Eis.',
  'Koroit-Boulder-Opal': 'Ein Feuerwerk im Gestein.',
  'Goldberyll': 'Gold, das nicht protzen muss.',
  'Iolith': 'Der Kompass der Wikinger – jetzt deiner.',
  'Achroit': 'Farblos? Nein, kompromisslos.',
  'Beryll': 'Aus der Familie der Smaragde. Du gehörst dazu.',
  'Welo-Opal': 'Regenbogen zum Mitnehmen.',
  'Sugilith': 'Violett, so selten wie Ruhe im Club.',
  'Rhodolith': 'Rosenrot mit Granat-Seele.',
  'Türkis': 'Seit den Pharaonen ein Zeichen von Macht.',
  'Kunzit': 'Zartrosa und trotzdem laut.',
  'Andalusit': 'Wechselt den Blick, nicht den Stil.',
  'Titanit': 'Mehr Feuer als ein Diamant.',
  'Morganit': 'Pfirsich, Rosé und ein Hauch Luxus.',
  'Peridot': 'Aus Vulkanen geboren.',
  'Rhodonit': 'Rosa mit schwarzen Linien – wie ein Tattoo.',
  'Siberit': 'Sibirisches Rot, heiß im Herzen.',
  'Apatit': 'Neonblau, das niemand übersieht.',
  'Sternsaphir': 'Du trägst einen Stern. Wortwörtlich.',
  'Rubellit': 'Rot wie ein Abend, den keiner vergisst.',
  'Yowah-Boulder-Opal': 'Das Outback hat seine Farben versteckt. Bei dir.',
  'Bicolor-Turmalin': 'Zwei Seiten, beide stark.',
  'Turmalin': 'Der Stein, der jede Farbe kann.',
  'Verdelith': 'Grün, das Eindruck macht.',
  'Goldtopas': 'Goldener Moment, festgehalten.',
  'Boulder-Opal': 'Feuer im Fels.',
  'Hessonit': 'Zimt, Honig und ein Hauch Orient.',
  'Zirkon': 'Älter als die Berge. Funkelt wie neu.',
  'Aquamarin': 'Meerwasser, in Stein gefasst.',
  'Opal': 'Jeder Blick ein neues Farbspiel.',
  'Pyrop': 'Feuerrot – der Name sagt es schon.',
  'Spessartin': 'Mandarine mit Strahlkraft.',
  'Indigolith': 'Tiefblau und selten wie Stille.',
  'Feueropal': 'Brennt, ohne zu verglühen.',
  'Crystal Opal': 'Klar wie Glas, bunt wie ein Festival.',
  'White Opal': 'Weiß, aber niemals farblos.',
  'Chrysoberyll': 'Goldgrün und härter als die meisten.',
  'Imperial-Topas': 'Für Zaren gemacht. Jetzt für dich.',
  'Chromturmalin': 'Smaragdgrün, aber mit eigenem Kopf.',
  'Sternrubin': 'Ein Stern in Rot. Mehr Fame geht kaum.',
  'Spinell': 'Lange für einen Rubin gehalten. Jetzt selbst ein Star.',
  'Black Crystal Opal': 'Dunkelheit voller Farben.',
  'Gelber Saphir': 'Sonnenlicht mit Saphir-Härte.',
  'Tansanit': 'Nur an einem Ort der Welt gefunden.',
  'Semi Black Opal': 'Halb Nacht, ganz Feuerwerk.',
  'Tsavorit': 'Grüner als jeder Neid.',
  'Jeremejewit': 'So selten, dass kaum einer den Namen kennt.',
  'Black Opal': 'Der König der Opale.',
  'Grüner Saphir': 'Grün, mit der Härte eines Saphirs.',
  'Padparadscha-Saphir': 'Lotusblüte im Sonnenuntergang.',
  'Demantoid': 'Funkelt feuriger als ein Diamant.',
  'Violetter Saphir': 'Violett, edel, unaufgeregt.',
  'Saphir': 'Blau wie ein Kronjuwel.',
  'Rosa Saphir': 'Rosa mit Rückgrat.',
};

// Brechzahl und Farbaufspaltung ("Feuer") je Steinart – bestimmen, wie das Licht im Stein läuft.
const OPTICS = [
  [/Diamant|Pink|Blue|Jewel|Constellation|Lesedi/, 2.42, 0.024],
  [/Demantoid/, 1.89, 0.034],
  [/Titanit/, 1.95, 0.034],
  [/Zirkon/, 1.95, 0.022],
  [/Saphir|Rubin/, 1.77, 0.009],
  [/Granat|Pyrop|Spessartin|Rhodolith|Hessonit|Tsavorit/, 1.76, 0.012],
  [/Spinell|Chrysoberyll|Alexandrit/, 1.74, 0.01],
  [/Peridot|Diopsid|Kyanit|Tansanit|Jeremejewit/, 1.68, 0.01],
  [/Topas|Andalusit|Apatit/, 1.62, 0.008],
  [/Turmalin|Verdelith|Indigolith|Rubellit|Siberit|Achroit/, 1.63, 0.009],
  [/Smaragd|Aquamarin|Beryll|Morganit/, 1.58, 0.007],
];
for (const g of GEM_LIST) {
  if (SAYINGS[g.name]) g.flavor = SAYINGS[g.name];
  if (g.cut === 'cabochon') continue;
  if (CUTS[g.name]) g.cut = CUTS[g.name];
  const o = OPTICS.find(([re]) => re.test(g.name));
  g.ior = o ? o[1] : 1.55;
  g.disp = o ? o[2] : 0.007;
}

// Sprüche je Seltenheitsklasse, falls ein Stein keinen eigenen hat
export const BAND_FLAVOR = [
  'Jeder fängt mal klein an.',
  'Ein Funkeln, das auffällt.',
  'Jetzt schauen die Leute hin.',
  'Selten. Wie du.',
  'Kaum einer hat ihn. Du schon.',
];

// Stufe -> Seltenheitsklasse (0..4): bestimmt Sound und Effekte – nicht den Stein selbst.
export function bandFor(stage) {
  return stage <= 25 ? 0 : stage <= 50 ? 1 : stage <= 70 ? 2 : stage <= 82 ? 3 : 4;
}
